### ISSUE TITLE
Implement Github Actions for Linting 

### ISSUE THREAD

**Issue by marianfoo** [1DSAG/UI5-Best-Practice#107]
In order to ensure a good general and consistent quality of the contributions there should be a review in the Github Actions.
For this purpose, a new Github action is created that checks various things.
For this severall PR are created. Here is a list in which order these PR should be merged.  
Still, merge erros will probably happen.

## 1. Fixing Linting Errors
- [x]  #102 
- [x]  #103
- [x]  #105
## 2. Adding Typescript
- [x]  #104
## 3. Linting Actions
- [x] #106
## 4. Create PDFs (optional)
- [x] #101 
## 5. Create Documentation about Linting
- [x] #112 
- [x] #109

**Comment by marianfoo** [comment]
@vobu would be great of you have some time to spare so you can have a look at this

**Comment by vobu** [comment]
grrreat initiative, thanks @marianfoo!
couple of things:
- i'm all pro linting markdown content, "self-discipline for producing valid md" FTW! this needs very careful communication towards the contributors and very well documented rules what is considered "valid markdown" (b/c there are so many flavors out there...). when we stick with [gh flavored markdown](https://github.github.com/gfm/), we should be good documentation-wise though ;)
- if scripting is involved that expands the tech stack of this project (like introducing TS for pdf-generation), I'd really like to see Deno being used: https://deno.land -> there's a lot benefit to gain (including ootb TS support 😸) from deno

**Comment by marianfoo** [comment]
> * i'm all pro linting markdown content, "self-discipline for producing valid md" FTW! this needs very careful communication towards the contributors and very well documented rules what is considered "valid markdown" (b/c there are so many flavors out there...). when we stick with [gh flavored markdown](https://github.github.com/gfm/), we should be good documentation-wise though ;)

You are absolutely right. This must be well documented. By the way, we use kramdown. 
https://github.com/1DSAG/UI5-Best-Practice/blob/b3869ffc45312bc39b4f1b6f75f5aa617e345e6f/docs/_config.yml#L29
I will definitely explain how to run the tests locally by yourself.
You were already so foresighted and you inserted `markdown --fix`. I will explain that as well.
https://github.com/1DSAG/UI5-Best-Practice/blob/b3869ffc45312bc39b4f1b6f75f5aa617e345e6f/package.json#L39

> * if scripting is involved that expands the tech stack of this project (like introducing TS for pdf-generation), I'd really like to see Deno being used: https://deno.land -> there's a lot benefit to gain (including ootb TS support 😸) from deno

i will have look but i don´t see the benefits yet

**Comment by vobu** [comment]
> I will definitely explain how to run the tests locally by yourself.

urgh, sorry, my bad 🙄 

> You were already so foresighted and you inserted `markdown --fix`. I will explain that as well.

👍 

> > * if scripting is involved that expands the tech stack of this project (like introducing TS for pdf-generation), I'd really like to see Deno being used: https://deno.land -> there's a lot benefit to gain (including ootb TS support 😸) from deno
> 
> i will have look but i don´t see the benefits yet 

it's the future :) :) :) 
no, seriously, IMO (purely subjective) `deno` has a way lower hurdle both in usage and integration scenarios, yet all the benefits the combination of `tsc` and/or `ts-node` plus `node ...` holds. Plus being able to [generate standalone binaries for all major platforms (*nix, macOS, Win)](https://deno.land/manual@v1.18.0/tools/compiler) from scripts; and [compile to `npm`-compatible CJS](https://github.com/denoland/dnt).

>if we switch to deno, we have to merge the PRs first because there are serveral PRs dependent on each other

yeah, let's do this first. And then we can continue then `deno` discussion. Eventually refactoring the TS files to `deno` is a small effort only.

**Comment by marianfoo** [comment]
@vobu 
Linting is green https://github.com/1DSAG/UI5-Best-Practice/actions/runs/1730730733
PDF creation does unfortunately not work because main is protected, maybe make it a manual action and perform it on a branch to merge it regularly

**Comment by marianfoo** [comment]
Linting on PR works
![image](https://user-images.githubusercontent.com/13335743/150648067-a7ac02af-1942-4d16-8754-cafb691e687d.png)

**Comment by marianfoo** [comment]
all tasks finished, improved docs in #112 and #109 
new issue created on the PDF problem #113 
For `Deno` a new issue create #114
