### ISSUE TITLE
Select DSAG logo and favicon

### ISSUE THREAD

**Issue by marianfoo** [1DSAG/UI5-Best-Practice#21]
As a start for the CI of DSAG we can already select a logo because this is already supplied by the theme.
Also a favicon would also be useful
I have already created a template here #22

**Comment by marianfoo** [comment]
@vobu @rotda 
Do we have access to various DSAG logos that we can use here?

**Comment by rotda** [comment]
Can you try this one ?
https://www.dsag.de/sites/default/files/2019-12/DSAG%20Logo.svg

**Comment by marianfoo** [comment]
@rotda that´s the one in #22
