### ISSUE TITLE
Usage of Block Inline Attribute Lists (IAL) not possible because of GFM

### ISSUE THREAD

**Issue by marianfoo** [1DSAG/UI5-Best-Practice#30]
Hi @vobu ,
I have seen in the documentation of our theme "Just the docs" many examples how to use CSS classes or the TOC in markdown.
So-called[ "Block Inline Attribute Lists"](https://kramdown.gettalong.org/syntax.html#block-ials) are used. 
https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/#in-page-navigation-with-table-of-contents
If you wanna increase the font-size for example, use using:
```
Font size 9
{: .fs-9 }
```
But since GitHub Flavored Markdown (GFM) is used in the config, these IALs cannot be utilised.
Github [supports two Markdown proccessor](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll): GFM and kramdown
After I set the Markdown processor to kramdown, it worked.

The IALs are apparently already useful and are also used by our theme.
Did you choose GFM for a special reason?

After the change to kramdown, I only noticed a few changes in the i18n area, which I would then correct.

**Comment by vobu** [comment]
i originally had chosen gh-flavored markdown as it provides slightly more editing capabilities than regular markdown (w/ kramdown) - e.g. tables, lists. but hey, i'm all cool with whatever gets the job done :) and your argument pro easier formatting is valid - let's take this into the meeting on fri.
