### ISSUE TITLE
include live code samples

### ISSUE THREAD

**Issue by marianfoo** [1DSAG/UI5-Best-Practice#46]
ideally, they can be run within the document.
evaluate observable hq for this?

**Comment by marianfoo** [comment]
Hi @vobu,
Can you please go into a bit more detail here, then I would take a look at it, it's a very good idea, but probably costly to maintain.

**Comment by vobu** [comment]
my initial idea here was to re-use https://observablehq.com notebooks - but i'd be fine with any other environment that allows for integrating coding into gh-docs/markdown

**Comment by marianfoo** [comment]
@vobu well, it´s not easy, but i managed to get a sample running
https://observablehq.com/@marianfoo/sample-ui5-app

**Comment by vobu** [comment]
wow, what an effort 💪 
but (admittedly only at a quick glance), not sure how sustainable this is. don't get me wrong: i 🧡 observable, but we should look at alternatives.
here's a suggestion: why not do a 1/2 day hackathon on the subject: "how to best get DSAG's best practice code samples running as live-preview'd code in jekyll?" participation open to anyone. I'd be game :)

**Comment by marianfoo** [comment]
I think it's a great tool, it could really be used to show live samples, especially the part that samples are reusable and forkable and it's embeddable via iframe.
Because of the reusablitity, the heavy lifiting can be done in advance.
So basically it's a good tool, but I also think there might be something better, I haven't looked yet.
I can ask for feedback on this example from our colleagues on Friday.

**Comment by marianfoo** [comment]
Positive Feedback on codesandbox.io
How to show Code? Runtime needed?
How to organize different topics?
How does the github repo look?
