### ISSUE TITLE
Add new Sponsor for topic "Fiori Elements vs. Free-Style"

### ISSUE THREAD

**Issue by marianfoo** [1DSAG/UI5-Best-Practice#49]
Unfortunately, no contributor was found for the topic "Fiori Elements vs. Free-Style".
This issue should find a sponsor for it and be linked to the pull request

**Comment by marianfoo** [comment]
Hello @QP-NaUh and @t-kessel ,
what is the current status here?
Do you need help here or can I support you somehow?

**Comment by t-kessel** [comment]
Hi @marianfoo 
The article about Fiori Elements vs. Freestyle is added to the document. 
You can merge the pull request by reviewing.

**Comment by marianfoo** [comment]
Hi @t-kessel 
thanks for the first content.
@QP-NaUh you can continue on this topic with content from @t-kessel

**Comment by QP-NaUh** [comment]
@marianfoo Yes, thank you.
I'm working on the topic.

**Comment by marianfoo** [comment]
Hi @QP-NaUh ,
bist du schon dazu gekommen am Thema weiter zu arbeiten?
Kann ich dich irgendwie unterstützen, evtl. am Inhalt den du schon hast weiter zu arbeiten?
