### ISSUE TITLE
Add new Sponsor for topic "Anotations XML vs Backend"

### ISSUE THREAD

**Issue by marianfoo** [1DSAG/UI5-Best-Practice#50]
Unfortunately, no contributor was found for the topic "Anotations XML vs Backend".
This issue should find a sponsor for it and be linked to the pull request

**Comment by vobu** [comment]
give overview and/or guidance that tech stack at hand decides on what annotation capabilities can or should be used.

RAP (Steampunk, S/4), NW ABAP, CAP (Java, Node.js) - local annotations.xml
