### ISSUE TITLE
Custom Control / Validations / Ext. Libraries

### ISSUE THREAD

**Issue by marianfoo** [1DSAG/UI5-Best-Practice#61]

**Comment by marianfoo** [comment]
Hi @rocketscience-dev 
as i saw in your e-mail, you are currently working on this one, right?

**Comment by marianfoo** [comment]
Hi @rocketscience-dev,
what is the current status here?
Do you need support in any form?

**Comment by rocketscience-dev** [comment]
Correctly. Basically, only small things are missing - otherwise I can send you the Word file. I had written example code for the code snippets - this was unfortunately deleted during a migration to another BTP account. I saved some as a screenshot - will try to fix this over the weekend.

**Comment by marianfoo** [comment]
I can help you to create the Pull Requests and you can review it.
Just send me the word file when you´re ready.
My plan was to write something here as well so i might can contribute something here.
