### ISSUE TITLE
Deployments

### ISSUE THREAD

**Issue by marianfoo** [1DSAG/UI5-Best-Practice#75]
BTP and on Premise
which Fiori Tools to use?
@osigge

**Comment by gregorwolf** [comment]
Isn't your question for On Premise answered with https://1dsag.github.io/UI5-Best-Practice/deployments/?

**Comment by marianfoo** [comment]
Hi @gregorwolf ,
nice to see you here.
The ticket here is just a reminder that Oliver would like to add information here.
The text is only from our meeting.
