### ISSUE TITLE
Modernize sample ErrorHandler

### ISSUE THREAD

**Issue by mschleeweiss** [1DSAG/UI5-Best-Practice#99]
Thanks to @t-kessel for setting up the sample error handler. A lot of work has gone into this. I think the code could be improved by introducing some ES6 features and applying other best practices from UI5 (e.g. no usage of sync components (like new sap.m.Button)). Would this be a welcome change or is the code like this on purpose (e.g. to run the code in IE11 without a complex babel setup)?

**Comment by marianfoo** [comment]
You are more than welcome to make improvements here.
I have created a sample app from the code of @t-kessel .
https://github.com/1DSAG/UI5-Best-Practice-samples/tree/error-handling
If you want to improve something here, then on the example app and in the guide.
I personally wouldn't look at IE11 anymore, but we can discuss that in the next meeting.
For all I care, you can already bring ES6 in here.
